# Generated by Django 5.2 on 2025-04-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="images/original/")),
                (
                    "edited_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/edited/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
